0. Итераторы
1. Что происходит при throw?
    - Экстренный выход из функции:
    - Уничтожаются все переменные (в обратном порядке к порядку создания)
    - Выходим из функции без возвращаемого значения
    - Выходим из функции, и дальше по аналогии в другой функции
    - Вплоть до мейна, там std::terminete 
2. [] & at == SegFault & Exception
    - Можно поймать & нельзя поймать..
    - 2 оператора проверяют dynamic_cast (std::bad_cast), new (std::bad_alloc)
3. 
